# General Jekyll Config
# See https://jekyllrb.com/docs/configuration/options/ for more options
name: Personal Lines Funtions
description: Data Science - Repo for ______
url: https://jdgrogan338.github.io/Personal_Lines_Functions/
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]
lsi: false

# Build Settings
theme: minima
# remote_theme: pages-themes/PrimeR
# Architect
# Cayman
# Dinky
# Hacker
# Leap day
# Merlot
# Midnight
# Minima
# Minimal
# Modernist
# Slate
# Tactile
# Time machine