# General Jekyll Config
# See https://jekyllrb.com/docs/configuration/options/ for more options
name: Personal Lines Funtions
description: Data Science - Repo for ______
url: https://...
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]
lsi: false

# Build Settings
remote_theme: thehartford/minima